# Copyright 2024 - TODAY, Kaynnan Lemes <kaynnan.lemes@escodoo.com.br>
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).


species_to_document_type = {
    # Purchase (Entrada)
    "1": 1,  # Nota Fiscal (Purchase Invoice)
    "2": 1,  # NF Avulsa (Purchase Invoice)
    "6": 1,  # Nota Fiscal de Produtor (Purchase Invoice)
    "7": 1,  # NF Conta de Energia Elétrica (Purchase Invoice)
    "26": 1,  # Conhec. Transp. Multimodal Carg (Purchase Invoice)
    "27": 1,  # NF Conta de Fornec. Água Can. (Purchase Invoice)
    "28": 1,  # NF Conta de Fornec. Gás Can. (Purchase Invoice)
    "36": 1,  # Nota Fiscal de Entrada (Purchase Invoice)
    # Sale (Saída)
    "3": 2,  # NFC-e (Sales Invoice)
    "4": 2,  # CF Cupom Fiscal (Sales Invoice)
    "5": 2,  # Bilhete Passagem emitido ECF (Sales Invoice)
    "8": 2,  # NF Serviço de Transporte (Sales Invoice)
    "9": 2,  # NF Serviço de Comunicação (Sales Invoice)
    "10": 2,  # Conhec. Transp. Rod. Carga (Sales Invoice)
    "11": 2,  # Conhec. Transp. Aquav. Carga (Sales Invoice)
    "12": 2,  # Conhecimento Aéro (Sales Invoice)
    "13": 2,  # Conhec. Transp. Ferrov. Cargas (Sales Invoice)
    "14": 2,  # Bilhete Passagem Rodoviário (Sales Invoice)
    "15": 2,  # Bilhete Passagem Aquaviário (Sales Invoice)
    "16": 2,  # Bilhete Passagem e NF Bagagem (Sales Invoice)
    "17": 2,  # Bilhete Passagem Ferroviário (Sales Invoice)
    "18": 2,  # Despacho de Transporte (Sales Invoice)
    "19": 2,  # Resumo Movimento Diário (Sales Invoice)
    "20": 2,  # Ordem de Coleta de Cargas (Sales Invoice)
    "22": 2,  # NF de Serviço de Telecomun. (Sales Invoice)
    "23": 2,  # GNRE (Sales Invoice)
    "24": 2,  # Autorizaçãoo de Carregamento e Transporte (Sales Invoice)
    "25": 2,  # Manifesto de Carga (Sales Invoice)
    "29": 2,  # Manifesto de Vôo (Sales Invoice)
    "30": 2,  # Bilhete Recibo do Passageiro (Sales Invoice)
    "32": 2,  # NF de Serviços - Mod. Simplif. (Sales Invoice)
    "33": 2,  # NF de Serviços - Mod. Avulsa (Sales Invoice)
    "35": 2,  # NF Modelo 2 (Sales Invoice)
    "37": 2,  # Nota Fiscal Eletrônica Avulsa (Sales Invoice)
    "38": 2,  # NF-e (Sales Invoice)
    # Service (Serviço)
    "21": 4,  # NF de Serviço de Comunicaçãoo (Service Invoice)
    "31": 4,  # NF de Serviços (Service Invoice)
    "34": 4,  # Nota Fiscal de Serviço (Service Invoice)
    "39": 4,  # NFS-e
}
